[package]
name = "gooey-git"
version = "0.1.0"
edition = "2021"
description = "A minimalist GUI git application"
authors = ["GooeyGit <gooey.git@example.com>"]

[dependencies]
gtk4 = "0.7"
git2 = "0.17"
libadwaita = "0.5"
once_cell = "1.18"
chrono = "0.4" 